/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "sb-bg-base": "var(--sb-bg-base)",
        "sb-bg-surface-1": "var(--sb-bg-surface-1)",
        "sb-bg-surface-2": "var(--sb-bg-surface-2)",
        "sb-bg-surface-3": "var(--sb-bg-surface-3)",
        "sb-border-hairline": "var(--sb-border-hairline)",
        "sb-border-hairline-strong": "var(--sb-border-hairline-strong)",
        "sb-border-focus": "var(--sb-border-focus)",
        "sb-text-primary": "var(--sb-text-primary)",
        "sb-text-secondary": "var(--sb-text-secondary)",
        "sb-text-tertiary": "var(--sb-text-tertiary)",
        "sb-accent": "var(--sb-accent)",
        "sb-accent-hover": "var(--sb-accent-hover)",
        "sb-accent-active": "var(--sb-accent-active)",
        "sb-accent-muted": "var(--sb-accent-muted)",
        "sb-verdict-build": "var(--sb-verdict-build)",
        "sb-verdict-build-bg": "var(--sb-verdict-build-bg)",
        "sb-verdict-conditional": "var(--sb-verdict-conditional)",
        "sb-verdict-conditional-bg": "var(--sb-verdict-conditional-bg)",
        "sb-verdict-avoid": "var(--sb-verdict-avoid)",
        "sb-verdict-avoid-bg": "var(--sb-verdict-avoid-bg)",
        "sb-verdict-kill": "var(--sb-verdict-kill)",
        "sb-verdict-kill-bg": "var(--sb-verdict-kill-bg)",
        "sb-evidence-evidenced": "var(--sb-evidence-evidenced)",
        "sb-evidence-suggestive": "var(--sb-evidence-suggestive)",
        "sb-evidence-assumed": "var(--sb-evidence-assumed)",
        "sb-prosecution-bg": "var(--sb-prosecution-bg)",
        "sb-defence-bg": "var(--sb-defence-bg)",
      },
      spacing: {
        "sb-1": "var(--sb-space-1)",
        "sb-2": "var(--sb-space-2)",
        "sb-3": "var(--sb-space-3)",
        "sb-4": "var(--sb-space-4)",
        "sb-5": "var(--sb-space-5)",
        "sb-6": "var(--sb-space-6)",
        "sb-8": "var(--sb-space-8)",
        "sb-10": "var(--sb-space-10)",
        "sb-12": "var(--sb-space-12)",
        "sb-16": "var(--sb-space-16)",
        "sb-20": "var(--sb-space-20)",
        "sb-24": "var(--sb-space-24)",
      },
      borderRadius: {
        "sb-sm": "var(--sb-radius-sm)",
        "sb-md": "var(--sb-radius-md)",
        "sb-lg": "var(--sb-radius-lg)",
        "sb-pill": "var(--sb-radius-pill)",
      },
      fontFamily: {
        "sb-display": ["var(--sb-font-display)"],
        "sb-body": ["var(--sb-font-body)"],
        "sb-mono": ["var(--sb-font-mono)"],
      },
      transitionDuration: {
        "sb-fast": "var(--sb-duration-fast)",
        "sb-base": "var(--sb-duration-base)",
        "sb-settle": "var(--sb-duration-settle)",
      },
      transitionTimingFunction: {
        "sb-standard": "var(--sb-ease-standard)",
      },
    },
  },
  plugins: [],
}
