export const productCopy={
 positioning:"SignalFit tells you if your idea is worth building — buyer pain, competition, pricing, risks, MVP scope, and a step-by-step plan to get your first customers. All in one report.",
 hero:{headline:"Stop building products\nnobody wants.",subheadline:"Describe your idea. Get a market-backed verdict — Build Now, Validate First, Niche Down, or Avoid — before you write a single line of code.",primaryCta:"Validate your idea",secondaryCta:"See a sample report"},
 problem:{title:"Most products fail because nobody checked if buyers exist.",body:"Not because the code was bad. Not because the team was weak. Because nobody verified the pain, the pricing, the competition, or the distribution before building. SignalFit checks all of it in minutes."},
 mechanism:{title:"One report. Every answer you need before building.",body:"SignalFit scans real market signals from Reddit, Product Hunt, G2, app reviews, competitor pricing pages, and founder communities. Then it scores your idea, identifies risks, maps competition, and tells you exactly what to do next."},
 trust:{title:"Every conclusion has evidence. Every score is explainable.",body:"No black-box AI opinions. Every finding links to a real source. Every score shows what drives it. Every risk is visible. You see exactly why the verdict says what it says."},
 urgency:["Every week spent building on a wrong assumption is a week you can't get back.","Strong ideas routinely fail when the buyer is unreachable, the pain is tolerable, or the market is already locked down.","A validation report costs less than a day of wasted development. The wrong product costs months."],
 sample:{name:"Recruiter Resume Reformatting Engine",verdict:"Validate First",score:"82/100",summary:"Strong B2B workflow pain, clear willingness to pay, and a direct outreach path. Primary risk: document parsing accuracy across messy PDFs and custom agency templates."},
 features:[["Buyer pain analysis","Find out if real people actually have this problem — and how badly they want it solved."],["Competition breakdown","See who you're up against, what they charge, and where the gaps are."],["Pricing intelligence","Know what buyers will pay before you set a price. Anchored to real competitive data."],["Risk assessment","See the risks before they cost you weeks. Market, execution, platform, and distribution."],["MVP scope","Know exactly what to build first and what to skip. No feature creep."],["Launch playbook","Get a plan to reach your first 10 paying customers. Channels, outreach scripts, success metrics."],["Weighted scoring model","8 criteria scored against your constraints. Adjustable weights. Fully explainable."],["Decision-ready exports","Share reports with co-founders, investors, or clients. Markdown, PDF, JSON, CSV."],["Side-by-side comparison","Compare multiple ideas against the same criteria. Pick the strongest signal."],["5-verdict system","Build Now, Validate First, Niche Down, Weak Signal, or Avoid. Clear next steps for each."]],
 pricing:{Free:"One quick scan per month — enough to check if deeper research is worth it.",Builder:"Full validation reports for builders making deliberate product decisions.",Pro:"For teams running multiple research tracks with side-by-side comparison.",Studio:"For agencies and consultancies delivering research-backed recommendations to clients.",Pass:"A single full validation without a monthly commitment."},
 faq:[["How is this different from ChatGPT?","SignalFit follows a structured validation methodology: real market signal extraction, source-backed evidence, competitive mapping, weighted scoring, risk assessment, and concrete next steps. It produces decision reports, not conversation."],["Can this guarantee my idea will succeed?","No. A report reduces uncertainty by surfacing evidence, risks, and assumptions. It tells you what to test next — not whether to bet the house."],["Where does the data come from?","From public sources where buyers already talk: Reddit, G2, Product Hunt, Capterra, app reviews, competitor pricing pages, founder communities, and search trends. Every finding keeps its source link."],["Can I adjust the scoring model?","Yes. The Pro tier lets you adjust criterion weights so the score reflects your specific constraints — speed, risk tolerance, revenue goals."],["Who uses SignalFit?","Founders, indie hackers, product teams, venture studios, agency operators, and students who want structured evidence before committing build time."],["Is this good enough for client deliverables?","Yes. The Director tier includes polished exports and professional formatting for client-facing research."],["What should I do after getting my report?","Execute the recommended next step. Strong reports shorten the path to a paid commitment, a prototype decision, or a justified walk-away."],["How long does a validation take?","Quick scans take about 2 minutes. Full validation reports take about 5 minutes."]],
 microcopy:{empty:"You haven't validated any ideas yet. Describe your first idea and get a market-backed verdict in minutes.",loading:"Scanning real market signals and building your validation report.",error:"Something went wrong. Nothing was saved — you can retry when ready.",onboarding:"Describe your idea, who it's for, and what problem it solves. We'll do the rest.",export:"Your report is ready to share. Exports include full evidence, not just the summary.",tooltips:{confidence:"Confidence reflects how much evidence was found — not how likely the idea is to succeed.",weights:"Adjust weights to match what matters most to you: speed, revenue, risk tolerance, or distribution.",verdict:"A verdict is a recommended next action based on the evidence. Not a prediction."}}
} as const;
