export const productCopy = {
  positioning: "ShouldBuild screens product ideas with cited public-source evidence, a deterministic score, risks, pricing direction, and next actions.",
  hero: {
    headline: "Validate before you build.",
    subheadline: "Choose a Quick Scan or Full Validation and review the evidence, limitations, deterministic score, and official verdict before committing meaningful time or money.",
    primaryCta: "Run your free Quick Scan",
    secondaryCta: "See a Full Validation",
  },
  problem: { title: "Important product assumptions deserve evidence.", body: "ShouldBuild checks buyer pain, pricing, competition, and distribution assumptions against public-source evidence and labels limitations when support is weak." },
  mechanism: { title: "Two report depths for two decisions.", body: "Quick Scan is a useful screening report. Full Validation adds targeted, specialist, and adversarial research when the decision warrants deeper work." },
  trust: { title: "Citations and deterministic scoring stay inspectable.", body: "Report findings retain source links. The official 12-factor score and verdict come from code-owned scoring; generated narrative cannot override them." },
  urgency: ["Evidence can reveal costly assumptions before implementation.", "A report reduces uncertainty but does not guarantee demand, accuracy, or business success."],
  features: [
    ["Buyer pain analysis", "Review persisted evidence about the problem and current workaround."],
    ["Competition breakdown", "Inspect persisted competitor records, pricing references, strengths, and gaps."],
    ["Pricing direction", "Review evidence-linked pricing direction and validate it with real buyer behavior."],
    ["Risk assessment", "Review market, execution, platform, and distribution risks found by the report."],
    ["MVP scope", "Use the report's persisted scope and exclusions as hypotheses to validate."],
    ["12-factor scoring", "Inspect the deterministic factors, weights, notes, confidence, and verdict."],
    ["Mode-aware exports", "Quick Scan includes PDF; Full Validation includes PDF, Markdown, CSV, and JSON."],
    ["Report comparison", "Compare completed reports while accounting for different research depths."],
  ],
  pricing: {
    Free: "One monthly Quick Scan entitlement where eligible; no card required.",
    Builder: "Not launched.",
    Pro: "Subscription terms are not finalized.",
    Studio: "Team-plan terms are not finalized.",
    Pass: "One-off paid access is not available.",
  },
  faq: [
    ["Can this guarantee my idea will succeed?", "No. A report reduces uncertainty by surfacing evidence, risks, limitations, and assumptions."],
    ["Where does the data come from?", "From public web sources returned by configured research providers. Persisted findings retain their source links."],
    ["Can generated narrative change the official score?", "No. The official score and verdict come from the deterministic 12-factor scoring engine."],
    ["How long does a validation take?", "Processing time depends on provider and source availability. The progress page shows actual backend stages; no fixed processing time is promised."],
  ],
  microcopy: {
    empty: "You have not validated any ideas yet.",
    loading: "Research is running. The progress page reflects actual backend stages.",
    error: "The run did not complete. Review the recorded error before retrying.",
    onboarding: "Describe your idea, intended buyer, and problem precisely.",
    export: "Only export formats stored for this report type are available.",
    tooltips: {
      confidence: "Confidence reflects persisted evidence coverage and quality, not the probability of success.",
      weights: "Weights control the deterministic contribution of each factor.",
      verdict: "A verdict is a recommended next action based on the score and evidence, not a prediction.",
    },
  },
} as const;
