export const productCopy={
 positioning:"SignalFit turns a raw product idea into a structured decision memo — buyer evidence, competitive pressure, pricing logic, and the one test worth running next. Stop guessing. Start knowing.",
 hero:{headline:"Know the answer before you write the code.",subheadline:"SignalFit produces structured research memos — buyer evidence, market context, competitive pressure, pricing logic, and the one validation test that should happen next.",primaryCta:"Commission a memo",secondaryCta:"Read a sample memo"},
 problem:{title:"The most expensive mistake in product development is building before proving.",body:"Most products don't fail because of bad code. They fail because no one checked whether the buyer, the pain, the pricing, and the distribution were real. SignalFit makes those assumptions visible while they're still cheap to change."},
 mechanism:{title:"Structured research. Actionable conclusions.",body:"SignalFit traces public market signals, extracts source-backed evidence, maps competitive pressure, scores opportunity strength against adjustable criteria, and delivers a decision-ready memo with a concrete next step."},
 trust:{title:"Evidence first. Inference second. Assumptions always labelled.",body:"Every memo separates what is known, what is inferred, and what remains an untested assumption. The point is decision clarity — never manufactured certainty."},
 urgency:["Every week spent building on an untested assumption is a week unavailable for the right opportunity.","Strong ideas routinely fail when the buyer is unreachable, the pain is tolerable, or the market is already consolidated.","The cost of a wrong build decision compounds. The cost of a research memo does not."],
 sample:{name:"Recruiter Resume Reformatting Engine",verdict:"Validate First",score:"82/100",summary:"Strong B2B workflow pain, clear willingness to pay, and a direct outreach path. Primary risk: document parsing accuracy across messy PDFs and custom agency templates."},
 features:[["Source-backed evidence","Every finding links to a traceable public source — not a generated opinion."],["Pain severity analysis","Identify repeated buyer frustration and the specific workflow it disrupts."],["Competitive teardown","Map incumbent strengths, weaknesses, and the gaps worth attacking."],["Weighted decision model","Make tradeoffs explicit, adjustable, and explainable against your criteria."],["MVP boundary definition","Define the smallest credible test — and the features that haven't earned inclusion."],["Pricing logic","Test a price point against existing buyer spend and competitive anchors."],["First 10 customers plan","Move from a research conclusion to a specific, actionable outreach strategy."],["Risk assessment","Separate market, execution, platform, and distribution risks before scope expands."],["Decision-ready exports","Share a structured memo with partners, stakeholders, or advisory boards."],["Comparative analysis","Hold competing opportunities to the same evidence standard."]],
 pricing:{Free:"One signal scan — enough to determine whether deeper research is warranted.",Builder:"Structured validation for builders making deliberate product decisions.",Pro:"For teams running multiple research tracks and needing deeper comparative analysis.",Studio:"For agencies and consultancies delivering research-backed recommendations to clients.",Pass:"A single deep analysis without a recurring commitment."},
 faq:[["How does this differ from ChatGPT?","SignalFit follows a structured validation methodology: public signal extraction, source-backed evidence handling, competitive mapping, weighted scoring, risk assessment, and concrete next-step recommendations. It produces decision memos, not conversation."],["Can this guarantee my idea will succeed?","No. A memo is structured decision support. It identifies what is evidenced, what is inferred, and what requires direct market testing before commitment."],["Where does the research data originate?","From configured public-source search and extraction providers. Every evidence item retains its source context, date, and confidence level."],["Can I adjust the scoring criteria?","Yes. Criterion weights reflect your specific revenue target, risk tolerance, and distribution advantage. The model normalizes automatically."],["Who uses SignalFit?","Founders, product leads, indie builders, venture studios, and consulting teams who want structured evidence before committing build time."],["Is this suitable for client deliverables?","Yes. The Director tier includes white-label exports and client-ready formatting for professional research workflows."],["How is this different from a market research report?","It's built to end in a product decision: what to validate, what to build first, what to avoid, and how to reach the first paying customers."],["What should I do after receiving a memo?","Execute the recommended next test. A strong memo shortens the path to a paid commitment, a prototype decision, or a justified walk-away."]],
 microcopy:{empty:"Begin with the opportunity that warrants investigation. We'll surface the hidden assumptions and the next evidence-gathering step.",loading:"Tracing public market signals and separating evidence from assumption.",error:"Research could not be initiated. Nothing has been saved — retry when ready.",onboarding:"Provide the buyer, the workflow, and the constraint that matters most. We'll structure the investigation.",export:"Your memo is ready to share. Exports include the full evidence context, not just the summary score.",tooltips:{confidence:"Confidence reflects evidence coverage and source quality — not likelihood of commercial success.",weights:"Adjust weights to reflect your specific definition of a worthwhile opportunity.",verdict:"A verdict is a recommended next action, not a prediction of outcomes."}}
} as const;
