import { z } from "zod";
import { scoringCriteria } from "./scoring";
import { Competitor, EvidenceItem, LaunchPlan, MVPPlan, OpportunityScorecard, PricingModel, RiskItem } from "./types";

export const evidenceSchema = z.object({ id: z.string(), source: z.string(), sourceType: z.string(), title: z.string(), snippet: z.string(), url: z.string().url().or(z.string().startsWith("/")), signal: z.enum(["Pain", "Demand", "Pricing", "Risk"]), strength: z.enum(["High", "Medium", "Low"]), date: z.string() });
export const competitorSchema = z.object({ id: z.string(), name: z.string(), positioning: z.string(), pricing: z.string(), target: z.string(), strength: z.string(), gap: z.string() });
export const pricingModelSchema = z.object({ model: z.string(), pricePoint: z.string(), rationale: z.string(), firstOffer: z.string(), targetCustomers: z.number().int().nonnegative() });
export const launchPlanSchema = z.object({ firstCustomerChannel: z.string(), weekOne: z.array(z.string()).min(1), outreachMessage: z.string(), successMetric: z.string(), firstTenStrategy: z.array(z.string()).min(1) });
export const riskSchema = z.object({ id: z.string(), category: z.enum(["Market", "Execution", "Platform", "Regulatory"]), severity: z.enum(["High", "Medium", "Low"]), description: z.string(), mitigation: z.string() });
export const mvpPlanSchema = z.object({ outcome: z.string(), scope: z.array(z.string()).min(1), exclusions: z.array(z.string()), buildEstimate: z.string(), buildComplexity: z.enum(["Low", "Medium", "High"]) });
export const scorecardSchema = z.object({ scores: z.object(Object.fromEntries(scoringCriteria.map(c => [c.key, z.number().min(0).max(100)])) as Record<string, z.ZodNumber>), notes: z.object(Object.fromEntries(scoringCriteria.map(c => [c.key, z.string().min(1)])) as Record<string, z.ZodString>), evidenceRefs: z.record(z.string(), z.array(z.string())).default({}), weights: z.object(Object.fromEntries(scoringCriteria.map(c => [c.key, z.number().min(0)])) as Record<string, z.ZodNumber>), total: z.number().min(0).max(100), confidence: z.number().min(0).max(100), verdict: z.enum(["Build Now", "Validate First", "Niche Down", "Weak Signal", "Avoid"]) });
export const opportunitySchema = z.object({ id: z.string(), name: z.string(), oneLiner: z.string(), targetCustomer: z.string(), corePain: z.string(), market: z.string(), scorecard: scorecardSchema, evidence: z.array(evidenceSchema), competitors: z.array(competitorSchema), pricing: pricingModelSchema, mvp: mvpPlanSchema, launch: launchPlanSchema, risks: z.array(riskSchema), createdAt: z.string() });
export const validationReportSchema = z.object({ id: z.string(), version: z.literal("1.0"), generatedAt: z.string(), executiveSummary: z.string(), opportunity: opportunitySchema, methodology: z.string() });
export interface ReportOpportunity { id: string; name: string; oneLiner: string; targetCustomer: string; corePain: string; market: string; scorecard: OpportunityScorecard; evidence: EvidenceItem[]; competitors: Competitor[]; pricing: PricingModel; mvp: MVPPlan & { buildComplexity: "Low" | "Medium" | "High" }; launch: LaunchPlan & { firstTenStrategy: string[] }; risks: RiskItem[]; createdAt: string; }
export interface ValidationReport { id: string; version: "1.0"; generatedAt: string; executiveSummary: string; opportunity: ReportOpportunity; methodology: string; }
