import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";
import { SUPPORT_EMAIL } from "@/lib/pricing";

export const metadata: Metadata = { title: "Privacy Policy | ShouldBuild", description: "How ShouldBuild collects, uses, shares, secures, and retains account, research, and technical data." };

const sections: LegalSection[] = [
  { title: "Scope", paragraphs: ["This Policy applies to the ShouldBuild website, accounts, research tools, reports, exports, support communications, and related services. It does not govern third-party websites cited in reports or their independent privacy practices. Paid checkout and billing integrations are not currently active."] },
  { title: "Information we collect", bullets: ["Account and profile data such as name, email, profile image, authentication provider, account identifiers, onboarding answers, preferences, team membership, and account status.", "User Content such as product ideas, descriptions, audiences, markets, locations, pricing assumptions, constraints, project names, notes, research requests, feedback, reports, evidence, scores, citations, comparisons, and exports.", "Technical data such as IP address, browser, device, operating system, pages and features used, dates, times, sessions, referrals, research-run status, provider usage, errors, performance, security logs, and approximate location inferred from IP.", "Support communications, contact details, attachments you choose to send, and response history."], paragraphs: ["Supabase Auth handles authentication credentials. Google provides only profile information you authorize. ShouldBuild does not receive your Google password. Because paid checkout is unavailable, ShouldBuild does not currently collect product-transaction or payment-card data."] },
  { title: "How we use information", bullets: ["Create, authenticate, secure, and administer accounts.", "Process research, public evidence, reports, citations, comparisons, exports, report history, and current entitlements.", "Prevent fraud, duplicate free accounts, abuse, security threats, and quota circumvention.", "Diagnose failures and improve reliability, relevance, usability, and product security.", "Provide support and essential account, security, and service communications.", "Meet legal, regulatory, dispute, and compliance obligations."], paragraphs: ["We do not sell personal information and do not use User Content for targeted advertising."] },
  { title: "Legal bases", paragraphs: ["Where GDPR or UK GDPR applies, processing relies on contract, legitimate interests, consent where required, legal obligations, and the establishment, exercise, or defence of legal claims."] },
  { title: "Research and AI processing", paragraphs: ["Idea descriptions, grounded research prompts, extracted public-source content, structured evidence, and limited report context may be processed by Google Gemini. Relevant public evidence may also be retrieved directly from cited pages, GitHub, or Hacker News.", "We aim to send only information reasonably necessary for the task. These services operate under their own agreements and privacy practices. Do not use ShouldBuild as a confidential data room or submit information requiring a special data-processing agreement unless one has been expressly agreed in writing."] },
  { title: "How we share information", paragraphs: ["We may share information with Supabase for authentication, database, realtime, storage, and server functions; Vercel for hosting and delivery; Google when you select Google OAuth; and the research providers described above. Dodo Payments is not currently connected.", "Information may also be disclosed to professional advisers, authorities, courts, or regulators where reasonably necessary or legally required, or to a successor in a merger, financing, sale, or restructuring subject to appropriate safeguards. Aggregated or de-identified information may be shared where it does not reasonably identify an individual."] },
  { title: "International processing", paragraphs: ["ShouldBuild and its providers may process information outside your country. Where required, we rely on contractual safeguards, adequacy decisions, provider commitments, consent, or other lawful transfer mechanisms."] },
  { title: "Retention", paragraphs: ["Account, report, support, log, deletion, and backup retention periods require deployment-specific operational approval. Until those periods and deletion processes are verified, ShouldBuild does not promise a numerical deletion or retention window. Information may be retained where reasonably necessary for security, legal obligations, or claims."] },
  { title: "Security", paragraphs: ["We use reasonable technical and organizational safeguards, including authenticated access, database authorization policies, private report storage, encryption in transit, restricted server credentials, and operational logging. No service can guarantee absolute security; protect your credentials and use a secure device and network."] },
  { title: "Your choices and rights", paragraphs: [<>Depending on your location, you may request access, correction, deletion, portability, restriction, objection, consent withdrawal, or make a complaint to a data-protection authority. Contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. We may verify identity before fulfilling a request.</>] },
  { title: "Account deletion", paragraphs: [<>Request deletion through available account controls or by emailing <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. Deletion does not remove information that must be retained for legal, security, fraud-prevention, or claims purposes.</>] },
  { title: "Cookies and local storage", paragraphs: ["ShouldBuild uses necessary cookies or similar technologies for authentication, sessions, security, basic preferences, and report-checklist state. It does not currently use checkout or subscription cookies and does not currently use third-party advertising cookies. Non-essential analytics or marketing cookies will require updated disclosures and consent controls where applicable."] },
  { title: "Children", paragraphs: ["ShouldBuild is not intended for anyone under 18. If you believe a child has provided personal information, contact us so we can investigate and delete it where appropriate."] },
  { title: "Third-party links and policy changes", paragraphs: ["Reports may link to public websites we do not control. Review their policies before providing information. We may update this Policy as the service, providers, laws, or data practices change and will update the effective date and provide additional notice where required."] },
  { title: "Contact and grievances", paragraphs: [<>For privacy questions, rights requests, complaints, or grievances, contact ShouldBuild at <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>. ShouldBuild operates from India and is available at <a href="https://shouldbuild.app">shouldbuild.app</a>.</>] },
];

export default function PrivacyPage() { return <LegalPage eyebrow="Legal" title="Privacy Policy" summary="This Policy explains how ShouldBuild collects, uses, shares, secures, and retains personal information when you use the service." sections={sections}/>; }
