import { validationReports } from "@/lib/report-mocks";
import { ValidationReport } from "@/lib/report-schema";
import { EvidenceItem } from "@/lib/types";
import { createAnalysisProvider, createPageExtractor, createSearchProvider } from "./providers";
import { filterEvidence } from "./evidence";
import { generateSearchQueries } from "./queries";
import { ResearchRequest, PipelineRun, ResearchStage } from "./types";
import { researchStore } from "./store";

const wait=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
function update(id:string,stage:ResearchStage,progress:number,message:string,extra:Partial<PipelineRun>={}){return researchStore.update(id,{stage,progress,message,...extra});}
function chooseSeed(input: ResearchRequest){ const value=`${input.ideaName} ${input.ideaDescription}`.toLowerCase(); if(value.includes("visa")) return validationReports[1]; if(value.includes("stripe")||value.includes("payment")) return validationReports[2]; if(value.includes("designer")||value.includes("approval")) return validationReports[3]; if(value.includes("geo")||value.includes("generative")) return validationReports[4]; return validationReports[0]; }
function toReport(seed:ValidationReport,run:PipelineRun):ValidationReport { const evidence:EvidenceItem[]=run.evidence.map(item=>({id:item.id,source:item.source,sourceType:item.kind,title:item.title,snippet:item.snippet,url:item.url,signal:item.kind.includes("pricing")?"Pricing":item.kind.includes("risk")?"Risk":item.kind.includes("complaint")||item.kind.includes("workaround")?"Pain":"Demand",strength:item.confidence>=70?"High":item.confidence>=50?"Medium":"Low",date:run.updatedAt.slice(0,10)})); const scorecard={...seed.opportunity.scorecard,evidenceRefs:Object.fromEntries(evidence.map((item)=>["painSeverity",[item.id]]))}; return {...seed,id:`report-${run.id}`,generatedAt:new Date().toISOString().slice(0,10),executiveSummary:`Mock-first research for ${run.request.ideaName}. ${seed.executiveSummary} Claims are limited to the collected evidence; all mock-provider signals require verification.`,opportunity:{...seed.opportunity,id:run.id,name:run.request.ideaName,oneLiner:run.request.ideaDescription,targetCustomer:run.request.targetCustomer,market:run.request.marketType,scorecard,evidence}}; }
export async function runResearchPipeline(id:string,input:ResearchRequest){ try { update(id,"generating_queries",10,"Generating focused search queries"); const queries=generateSearchQueries(input); await wait(120); update(id,"searching_web",22,`Searching ${queries.length} query variations`,{queries}); const search=await createSearchProvider().search(queries,input); await wait(150); update(id,"extracting_sources",43,`Extracting ${search.length} source pages`); const sources=await createPageExtractor().extract(search); await wait(120); update(id,"filtering_evidence",60,"Filtering duplicates and weak signals"); const evidence=filterEvidence(sources); update(id,"analyzing",74,`Analyzing ${evidence.length} evidence items`,{sources,evidence}); await createAnalysisProvider().analyze({ideaName:input.ideaName,ideaDescription:input.ideaDescription,targetCustomer:input.targetCustomer,marketType:input.marketType,targetRegion:input.targetRegion,evidence:evidence.map(e=>({id:e.id,kind:e.kind,snippet:e.snippet,source:e.source,url:e.url,confidence:e.confidence}))}); await wait(130); update(id,"scoring",84,"Applying weighted scoring framework"); await wait(120); update(id,"generating_report",93,"Assembling structured validation report"); const current=researchStore.get(id)!; const report=toReport(chooseSeed(input),{...current,evidence,sources}); await wait(100); update(id,"complete",100,"Report ready",{report,evidence,sources}); } catch(error) { update(id,"failed",100,"Research failed",{error:error instanceof Error?error.message:"Unknown pipeline error"}); } }
