import type { Metadata } from "next";
import { LegalPage, type LegalSection } from "@/components/legal/legal-page";
import { SUPPORT_EMAIL } from "@/lib/pricing";

export const metadata: Metadata = { title: "Terms of Service | ShouldBuild", description: "Terms governing use of ShouldBuild accounts, validation reports, credits, subscriptions, and exports." };

const sections: LegalSection[] = [
  { title: "Eligibility", paragraphs: ["You must be at least 18 years old and legally capable of entering a binding agreement. If you use ShouldBuild for an organization, you represent that you have authority to bind that organization."] },
  { title: "What ShouldBuild provides", paragraphs: ["ShouldBuild is an evidence-backed product and market-validation tool. It searches public sources, structures evidence, analyzes market signals, generates scores and recommendations, and creates cited reports and exports.", "ShouldBuild is decision support, not a guarantee of business success or report accuracy. Reports may contain errors, omissions, outdated information, conflicting evidence, or machine-generated interpretations. Independently verify important claims. The service is not legal, financial, investment, tax, accounting, medical, or other regulated professional advice."] },
  { title: "Accounts and security", paragraphs: [<>Provide accurate account information, protect your credentials, and promptly email <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> if you believe your account is compromised.</>, "We may suspend accounts involved in fraud, unlawful activity, security threats, repeated payment disputes, quota circumvention, or violations of these Terms."] },
  { title: "User submissions and confidentiality", paragraphs: ["You retain ownership of your ideas and other content. You grant ShouldBuild a limited, worldwide, non-exclusive licence to host, copy, process, transmit, analyze, transform, and display that content only as reasonably necessary to operate, secure, improve, and support the service.", "The research pipeline uses third-party search, extraction, embedding, and AI providers. Do not submit trade secrets, unpublished patent material, passwords, regulated data, highly sensitive personal information, or confidential information you are not authorized to disclose. Similar ideas may be submitted independently; ShouldBuild does not promise exclusivity."] },
  { title: "Public sources and third-party content", paragraphs: ["Reports may quote, summarize, classify, or link to publicly available third-party sources. Those sources remain owned by their respective owners. Citations are provided for transparency and verification, not endorsement. You are responsible for restrictions applying to your use or redistribution of third-party content."] },
  { title: "Purchases, subscriptions, credits, and renewals", paragraphs: ["Dodo Payments acts as Merchant of Record and legal seller for applicable transactions. Prices, tax treatment, currency, billing period, included credits, and renewal terms are shown before purchase. Subscriptions renew automatically until cancelled.", "Quick Scan uses 1 credit and Full Validation uses 3 credits. Free credits do not roll over. Paid subscription credits roll over while active up to the published two-month cap. One-off credits are valid for 12 months and have no cash value.", "Annual plans are paid annually and credits are granted monthly. Cancellation stops the next renewal; access continues through the paid period, generated reports remain accessible, and unused subscription credits expire when that period ends."] },
  { title: "Technical failures and refunds", paragraphs: [<>Verified worker, persistence, provider-exhaustion, report-generation, or pre-usable-export failures restore the affected credit. A negative verdict or changed idea is not a technical failure. The <a href="/legal/refunds">Refund Policy</a> is incorporated into these Terms.</>] },
  { title: "Acceptable use", bullets: ["Do not use the service for unlawful, fraudulent, deceptive, defamatory, infringing, or abusive activity.", "Do not submit content you lack permission to process, upload malware, or compromise accounts, infrastructure, providers, or users.", "Do not bypass authentication, authorization, credits, billing, rate limits, quotas, or security controls, including by creating duplicate accounts.", "Do not scrape, systematically extract, reverse engineer, resell access, share seats beyond plan limits, or represent reports as independently audited or guaranteed.", "Do not use automated output for high-impact decisions about individuals without appropriate human review and lawful authority."] },
  { title: "Intellectual property and report use", paragraphs: ["ShouldBuild software, interface, branding, scoring methodology, report structure, documentation, and original content are owned by ShouldBuild or its licensors. Unless a plan expressly states otherwise, purchased reports may be used for personal or internal commercial decision-making. You may not resell, white-label, bulk publish, or create a competing database from reports without written permission."] },
  { title: "Availability and changes", paragraphs: ["Research depends on public websites and third-party providers that may be delayed, unavailable, blocked, inaccurate, or changed. We do not guarantee uninterrupted operation. We may update, limit, suspend, discontinue, or replace features for security, compliance, performance, cost, or quality, with reasonable notice where a material change negatively affects a paid plan."] },
  { title: "Warranty disclaimer", paragraphs: ["To the maximum extent permitted by law, the service is provided “as is” and “as available.” We disclaim implied warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, availability, and results. Nothing excludes a consumer right that cannot legally be excluded."] },
  { title: "Limitation of liability", paragraphs: ["To the maximum extent permitted by law, ShouldBuild and its operator are not liable for indirect, incidental, special, consequential, exemplary, or punitive damages, or lost profits, revenue, data, opportunities, goodwill, or business decisions.", "Total aggregate liability will not exceed the greater of fees paid for the service during the three months before the event giving rise to the claim or USD 50. These limits do not apply where liability cannot legally be limited."] },
  { title: "Termination", paragraphs: ["You may stop using the service and request account deletion. We may suspend or terminate access for material Terms violations, security or legal risk, non-payment, refund abuse, or conduct that could harm ShouldBuild, its providers, or users. Provisions that by their nature should survive will survive termination."] },
  { title: "Governing law and disputes", paragraphs: [<>These Terms are governed by the laws of India. Before filing a formal claim, contact <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a> and allow 30 days for an informal resolution attempt. Mandatory consumer rights and jurisdiction rules continue to apply.</>] },
  { title: "Contact", paragraphs: [<>ShouldBuild · India · <a href="https://shouldbuild.app">shouldbuild.app</a> · <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a></>] },
];

export default function TermsPage() { return <LegalPage eyebrow="Legal" title="Terms of Service" summary="These Terms govern access to and use of the ShouldBuild website, research tools, reports, subscriptions, credits, exports, and related services." sections={sections}/>; }
