import Link from "next/link";
import { ArrowRight, Bookmark, FileText, Gauge, Rocket, Sparkles } from "lucide-react";
import { AppShell } from "@/components/layout/app-shell";
import { StatCard } from "@/components/dashboard/stat-card";
import { ProjectCard } from "@/components/dashboard/project-card";
import { ScoreBadge } from "@/components/scoring/score-badge";
import { VerdictBadge } from "@/components/opportunity/verdict-badge";
import { compareOpportunities, researchRuns } from "@/lib/mock-data";
export default function DashboardPage(){return <AppShell title="Dashboard" action={<Link className="button button-small" href="/research/new">New research <ArrowRight size={15}/></Link>}><div className="page-content"><section className="dashboard-intro"><div><h2>Good morning, builder.</h2><p>Turn evidence into your next confident product decision.</p></div><div className="focus-card"><Sparkles size={16}/><span><b>Focus for this week</b><small>Validate the payment signal for CloseSignal.</small></span></div></section><section className="stats-grid"><StatCard icon={FileText} label="Total reports" value="12" detail="3 completed this month"/><StatCard icon={Gauge} label="Average score" value="68" detail="Across your saved ideas"/><StatCard icon={Bookmark} label="Saved ideas" value="07" detail="2 need more proof"/><StatCard icon={Rocket} label="Build-now verdicts" value="02" detail="Ready for customer tests"/></section><section className="split-section"><div className="section-card"><header><div><p className="eyebrow">Active projects</p><h2>Research workspace</h2></div><Link href="/research/new">Add idea <ArrowRight size={14}/></Link></header><div className="project-grid">{researchRuns.slice(0,2).map(run=><ProjectCard key={run.id} run={run}/>)}</div></div><div className="section-card recent-card"><header><div><p className="eyebrow">Recent research</p><h2>Latest runs</h2></div><Link href="/research/new">View all</Link></header>{researchRuns.map(run=><Link className="recent-run" href={run.opportunity?"/research/run_104/results":"/research/new"} key={run.id}><span>{run.mode}</span><b>{run.ideaName}</b><small>{run.createdAt}</small><ArrowRight size={14}/></Link>)}</div></section><section className="section-card opportunity-table"><header><div><p className="eyebrow">Ranked ideas</p><h2>Top scored opportunities</h2></div><Link href="/compare">Compare ideas <ArrowRight size={14}/></Link></header><div className="table-wrap"><table><thead><tr><th>Opportunity</th><th>Target customer</th><th>Score</th><th>Verdict</th><th></th></tr></thead><tbody>{compareOpportunities.map(o=><tr key={o.id}><td><b>{o.name}</b><small>{o.oneLiner}</small></td><td>{o.targetCustomer}</td><td><ScoreBadge score={o.score.total} size="sm"/></td><td><VerdictBadge verdict={o.verdict}/></td><td><Link href="/research/run_104/results"><ArrowRight size={15}/></Link></td></tr>)}</tbody></table></div></section></div></AppShell>}
