import Link from "next/link";
import { ArrowRight, CheckCircle2, ChevronRight, FileSearch, Gauge, Radar, ShieldCheck, Target } from "lucide-react";
import { Brand } from "@/components/layout/brand";

const signals = ["Founder communities", "Review sites", "Public pricing", "App stores", "Competitor pages", "Forums"];

export function LandingPage() {
  return <div className="bs-modern">
    <header className="bs-nav"><Brand/><nav><a href="#method">Method</a><a href="#report">Inside a memo</a><a href="#pricing">Membership</a></nav><div><Link href="/auth">Sign in</Link><Link className="bs-btn bs-btn-bright" href="/research/new">Start a brief <ArrowRight size={15}/></Link></div></header>
    <main>
      <section className="bs-hero">
        <div className="bs-hero-copy"><p className="bs-kicker"><Radar size={14}/> Founder intelligence / early-stage decisions</p><h1>Research the bet<br/>before you <span>build the thing.</span></h1><p>SignalFit turns a raw idea into a readable decision memo: buyer evidence, market context, competitor pressure, pricing logic, and the one test that should happen next.</p><div className="bs-actions"><Link className="bs-btn bs-btn-bright" href="/research/new">Open an investigation <ArrowRight size={16}/></Link><Link className="bs-link" href="/sample-report">Read a sample memo <ChevronRight size={15}/></Link></div><small><ShieldCheck size={14}/> Sources cited · inferences marked · certainty never invented</small></div>
        <MemoPreview/>
      </section>
      <section className="bs-signal-strip"><span>Evidence traceable to the places buyers already speak</span><div>{signals.map(signal => <b key={signal}>{signal}</b>)}</div></section>
      <section className="bs-proof" id="method"><div className="bs-section-head"><p className="bs-kicker">The pre-build discipline</p><h2>Make the costly questions answerable while the answer is still cheap.</h2><p>Founders rarely need more features. They need a clear view of the customer, the pain, the alternatives, and the proof required before more time gets committed.</p></div><div className="bs-loop"><Brief number="I" title="Frame the inquiry" text="Name the buyer, job, setting, and constraints behind the opportunity."/><Brief number="II" title="Follow the evidence" text="Trace complaints, workarounds, pricing, competition, and paths to the first conversation."/><Brief number="III" title="Choose a commitment" text="Leave with an explainable build, validate, narrow, or walk-away recommendation."/></div></section>
      <section className="bs-showcase" id="report"><div className="bs-section-head"><p className="bs-kicker">A memo you can challenge</p><h2>Every conclusion has somewhere to stand.</h2><p>Not a confident-looking wall of generated prose. A working document where evidence, interpretation, and open risk stay distinct.</p></div><MemoPreview expanded/><Link className="bs-btn bs-btn-outline" href="/sample-report">Read the full sample memo <ArrowRight size={15}/></Link></section>
      <section className="bs-value"><div className="bs-section-head"><p className="bs-kicker">Built for a founder&apos;s actual question</p><h2>Decision confidence, without decision theatre.</h2></div><div className="bs-value-grid"><Value icon={FileSearch} title="Evidence ledger" text="Keep buyer language, sources, dates, and confidence in one inspectable record."/><Value icon={Target} title="MVP boundary" text="Define the smallest credible test—and the features that have not earned their way in."/><Value icon={Gauge} title="Transparent model" text="Set the decision criteria and see how each opportunity performs against them."/><Value icon={ShieldCheck} title="Honest uncertainty" text="Separate what is known, inferred, and still worth testing before it costs you."/></div></section>
      <section id="pricing" className="bs-pricing"><div><p className="bs-kicker">Membership designed for real work</p><h2>The first memo is cheaper than a week of misplaced building.</h2><p>Start with one focused inquiry. Upgrade only when you need a deeper research cadence or client-ready decision material.</p></div><div className="bs-price-row"><span>Field note<b>$0</b><small>One fast signal scan</small></span><span className="active">Founder desk<b>$19</b><small>For repeated validation</small></span><span>Research office<b>$49</b><small>Comparison and exports</small></span><span>Studio desk<b>$149</b><small>Shared client work</small></span></div><Link className="bs-btn bs-btn-bright" href="/pricing">Review membership <ArrowRight size={15}/></Link></section>
      <section className="bs-final"><p className="bs-kicker">A quieter, better first move</p><h2>Before you build it,<br/>make the market answer for it.</h2><Link className="bs-btn bs-btn-bright" href="/research/new">Start an investigation <ArrowRight size={16}/></Link></section>
    </main><footer><Brand/><span>SignalFit · research before commitment.</span></footer>
  </div>;
}

function MemoPreview({ expanded = false }: { expanded?: boolean }) { return <div className={`bs-product-frame${expanded ? " expanded" : ""}`}><div className="bs-window"><header><span className="bs-window-dot"/><span>SIGNALFIT / RESEARCH MEMO 04</span><i>CONFIDENTIAL WORKING DRAFT</i></header><aside><b>04</b><span className="active">Executive view</span><span>Evidence ledger</span><span>Market map</span><span>Test design</span></aside><main><div className="bs-dashboard-top"><div><small>OPPORTUNITY INQUIRY</small><h3>Recruiter resume reformatting engine</h3></div><button>Memo complete</button></div><div className="bs-dashboard-stats"><Stat n="82" label="Signal strength"/><Stat n="68%" label="Evidence confidence"/><Stat n="12" label="Sources reviewed"/></div><div className="bs-dashboard-panel"><div><b>Preliminary conclusion</b><small>Validate first — clear workflow pain, with a narrow proof still required.</small><p><i/> Run a paid pilot around messy template variance.</p><p><i/> Speak with 5 agency owners before defining the MVP.</p></div><div className="bs-dashboard-panel score"><b>01</b><small>Immediate next test<br/>paid concierge pilot</small></div></div></main></div></div>; }
function Stat({ n, label }: { n:string; label:string }) { return <span><b>{n}</b><small>{label}</small></span>; }
function Brief({ number, title, text }: { number:string; title:string; text:string }) { return <article><span>{number}</span><h3>{title}</h3><p>{text}</p><CheckCircle2 size={16}/></article>; }
function Value({ icon: Icon, title, text }: { icon: typeof FileSearch; title:string; text:string }) { return <article><Icon size={18}/><h3>{title}</h3><p>{text}</p></article>; }
